name: Deploy GitHub Runner

on:
  push:
    branches:
      - main
      - test-13-june
  pull_request:
    branches:
      - main
      - test-13-june

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-west-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Print Environment Variables
        run: env

      - name: Plan Terraform
        env:
          TF_VAR_github_owner: ${{ secrets.GH_OWNER }}
          TF_VAR_github_repo: ${{ secrets.GH_REPO }}
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
          TF_VAR_runner_ami: ${{ secrets.RUNNER_AMI }}
          TF_VAR_instance_type: ${{ secrets.INSTANCE_TYPE }}
          TF_VAR_key_name: ${{ secrets.KEY_NAME }}
          TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
          TF_VAR_subnet_id: ${{ secrets.SUBNET_ID }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        run: terraform plan -var "github_owner=${{ secrets.GH_OWNER }}" -var "github_repo=${{ secrets.GH_REPO }}" -var "github_token=${{ secrets.GH_TOKEN }}" -var "runner_ami=${{ secrets.RUNNER_AMI }}" -var "instance_type=${{ secrets.INSTANCE_TYPE }}" -var "key_name=${{ secrets.KEY_NAME }}" -var "vpc_id=${{ secrets.VPC_ID }}" -var "subnet_id=${{ secrets.SUBNET_ID }}" -var "aws_region=${{ secrets.AWS_REGION }}" -out=plan.tfplan

      - name: Apply Terraform
        run: terraform apply -auto-approve plan.tfplan
